#-----------programas realizando calculos de tabuada--------------------------
#opção 01
tab = int(input('Digite um numero para ver sua tabuada aqui:'))
print(f'{tab}x0 = {tab*0}')
print(f'{tab}x1 = {tab*1}')
print(f'{tab}x2 = {tab*2}')
print(f'{tab}x3 = {tab*3}')
print(f'{tab}x4 = {tab*4}')
print(f'{tab}x5 = {tab*5}')
print(f'{tab}x6 = {tab*6}')
print(f'{tab}x7 = {tab*7}')
print(f'{tab}x8 = {tab*8}')
print(f'{tab}x9 = {tab*9}')

#opção 02
num = int(input('Digite um numero para ver sua tabuada:'))
print('-'*20)
print('{} x {} vale : {}'.format(num, 1, num*1))
print('{} x {} vale : {}'.format(num, 2, num*2))
print('{} x {} vale : {}'.format(num, 3, num*3))
print('{} x {} vale : {}'.format(num, 4, num*4))
print('{} x {} vale : {}'.format(num, 5, num*5))
print('{} x {} vale : {}'.format(num, 6, num*6))
print('{} x {} vale : {}'.format(num, 7, num*7))
print('{} x {} vale : {}'.format(num, 8, num*8))
print('{} x {} vale : {}'.format(num, 9, num*9))
print('{} x {} vale : {}'.format(num, 10, num*10))
print('-'*20)